### ISSUE TITLE
theme question in migration of docs content

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm-www#30]
What I am trying to do:

* Move the `docs` content from https://github.com/openservicemesh/osm/tree/main/docs/content/  to https://github.com/openservicemesh/osm-www/tree/main/content/

* Preserve any necessary configs from https://github.com/openservicemesh/osm/tree/main/docs

The problem I ran into:

I'm not sure how to deal with the differing theme, generated resources including scss assets, and the like. The docs site requires some partials from the dosmy theme, but attempting to move a few of those into the clean-landing theme is probably not the way to go, as it produces errors along the lines of:

_executing "partials/head-css.html" at <resources.ExecuteAsTemplate>: error calling ExecuteAsTemplate: type <nil> not supported in Resource transformations_

What I need:

Guidance as to what I _should_ be doing theme-wise to combine these two sites (openservicemesh.io and docs.openservicemesh.io) and serve the second one out of openservicemesh.io/docs just like openservicemesh.io/blog? (It would be fine to use a second theme and build it as a second site out of this repo, if combining the themes does not work easily.) 

Thanks!

**Comment by flynnduism** [comment]
Migrating the content is straightforward enough, but there will be a significant amount of work involved in merging these two sites together from a theme and config point of view.


# Two Sites, Two Themes

* OSM-www: uses a custom barebones theme `clean-landing`  
  _I've made this; a clean boilerplate I use as starting point for marketing site projects_  
* Docs site: `docsy` theme, with some custom stuff
  _This was chosen for OSM docs as it's tailored very specifically for docs layouts; sidebar menus, versioning, l18n, etc_

Basically they're two different codebases / designs, so one theme needs to be reworked to incorporate the custom views, params etc from the other one. It's doable, but in my experience it can be still take a while to complete and get everything smooth... we did this for Helm before v3 and it took awhile to get everything right. 

# Goals

When we made the docs site a few months ago this situation was discussed but avoided because (1) it was seen as beneficial to keep the docs content inside the project for the sake of preserving the dev workflow and (2) a smaller standalone codebase for the docs site was quicker to build and easier maintain than rebuilding the marketing/blog website to serve as a home for docs too.

Before embarking on such an effort, I'm trying to understand the goals for changing things around -

* Is there a desire to have one repo for the three different types of web content?
* Or is this moreso about keeping all the Hugo stuff out of the core project repo? 

If it's the later, it is much cleaner to just move itto a standalone docs repo than trying to merge two sites/themes together IMO.

**Comment by bridgetkromhout** [comment]
Thanks, Ronan! The goal is to have docs be docs, and avoid all the attempts at maintaining the links and site-nav between github and web views. A stand-alone docs repo is fine by me. Let's try that.

**Comment by bridgetkromhout** [comment]
I've opened a PR to migrate all docs from osm to osm-docs: https://github.com/openservicemesh/osm/pull/3318 - it will need modification but we can use that as a baseline for the content-move.

**Comment by bridgetkromhout** [comment]
Following this guidance from @flynnduism I set up https://github.com/openservicemesh/osm-docs and we're testing it in netlify. After confirming with the team we'll migrate.

**Comment by bridgetkromhout** [comment]
Everything worked! Thanks, @flynnduism!
